/*
    A user should:
        - Have a profile
            - contains:
                - First Name*
                - Last Name*
                - Email*
                    - display or Private, used to login
                - Address (City, State, Zip, Country)*
                - Password
                - Social Media handles
                    - options for:
                        - Twitter
                        - FB
                        - Instagram
                        - YouTube
                        - TikTok
                        - SnapChat
                - Role*
                    - Initial roles:
                        - Comic
                            - Bio
                            - Most recent clip
                            - Credits
                            - Points
                        - Host
                        - Producer
                            - contact email*
                            - Shows managed*
                                - show name
                                - show venue
                                - show start time
                            - contact phone
                        - Site Admin
                        - Super Admin (basically me/chad/bob)
                - Profile Image
                - Profile Header Image
                - options to login with major social auths
 */